// SPDX-FileCopyrightText: 2024 Firewatch <54725557+musicmanvr@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Mr. 27 <45323883+Dutch-VanDerLinde@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Mr. 27 <koolthunder019@gmail.com>
// SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Corvax.Interfaces.Shared;
using Content.Shared.Clothing;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;

namespace Content.Client.Lobby.UI.Loadouts;

[GenerateTypedNameReferences]
public sealed partial class LoadoutGroupContainer : BoxContainer
{
    private const string ClosedGroupMark = "▶";
    private const string OpenedGroupMark = "▼";

    /// <summary>
    /// A dictionary that stores open groups
    /// </summary>
    private Dictionary<string, bool> _openedGroups = new();

    private readonly LoadoutGroupPrototype _groupProto;

    public event Action<ProtoId<LoadoutPrototype>>? OnLoadoutPressed;
    public event Action<ProtoId<LoadoutPrototype>>? OnLoadoutUnpressed;

    public LoadoutGroupContainer(HumanoidCharacterProfile profile, RoleLoadout loadout, LoadoutGroupPrototype groupProto, ICommonSession session, IDependencyCollection collection)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _groupProto = groupProto;

        RefreshLoadouts(profile, loadout, session, collection);
    }

    /// <summary>
    /// Updates button availabilities and buttons.
    /// </summary>
    public void RefreshLoadouts(HumanoidCharacterProfile profile, RoleLoadout loadout, ICommonSession session, IDependencyCollection collection)
    {
        var protoMan = collection.Resolve<IPrototypeManager>();
        var loadoutSystem = collection.Resolve<IEntityManager>().System<LoadoutSystem>();
        RestrictionsContainer.DisposeAllChildren();

        if (_groupProto.MinLimit > 0)
        {
            RestrictionsContainer.AddChild(new Label()
            {
                Text = Loc.GetString("loadouts-min-limit", ("count", _groupProto.MinLimit)),
                Margin = new Thickness(5, 0, 5, 5),
            });
        }

        if (_groupProto.MaxLimit > 0)
        {
            RestrictionsContainer.AddChild(new Label()
            {
                Text = Loc.GetString("loadouts-max-limit", ("count", _groupProto.MaxLimit)),
                Margin = new Thickness(5, 0, 5, 5),
            });
        }

        if (protoMan.TryIndex(loadout.Role, out var roleProto) && roleProto.Points != null && loadout.Points != null)
        {
            RestrictionsContainer.AddChild(new Label()
            {
                Text = Loc.GetString("loadouts-points-limit", ("count", loadout.Points.Value), ("max", roleProto.Points.Value)),
                Margin = new Thickness(5, 0, 5, 5),
            });
        }

        LoadoutsContainer.DisposeAllChildren();

        // CorvaxGoob-Loadouts-Start
        var groupLoadouts = _groupProto.Loadouts;
        if (collection.TryResolveType<ISharedLoadoutsManager>(out var loadoutsManager) && _groupProto.ID == "Inventory")
        {
            groupLoadouts = loadoutsManager.GetClientPrototypes().Select(id => (ProtoId<LoadoutPrototype>) id).ToList();
        }
        // CorvaxGoob-Loadouts-End

        // Get all loadout prototypes for this group.
        var validProtos = groupLoadouts.Select(id => protoMan.Index(id)); // Corvax-Loadouts-Edit

        // Get all loadout prototypes for this group.
        //var validProtos = _groupProto.Loadouts.Select(id => protoMan.Index(id));

        /*
         * Nuclear-LoadoutGroupTree:
         * Loadouts are now grouped hierarchically based on the GroupBy list in LoadoutPrototype.
         * Each element in GroupBy represents one level of nesting.
         * For example, GroupBy: ["female", "color"] creates:
         *   ▼ female
         *     ▼ color
         *       [loadout items]
         *
         * If GroupBy is empty, the loadout is added directly without a subgroup.
         * For backwards compatibility, a single string (old format) is converted to a list of one element.
         *
         * The recursive BuildGroupTree method handles all nesting levels,
         * creating collapsible subgroups with toggle buttons at each level.
         */

        // Nuclear-LoadoutGroupTree-Start
        var validProtosList = validProtos.ToList();
        BuildGroupTree(LoadoutsContainer, validProtosList, 0, profile, loadout, session, collection, loadoutSystem);
        // Nuclear-LoadoutGroupTree-End
    }

    // Nuclear-LoadoutGroupTree-Start
    /// <summary>
    /// Recursively builds a tree of loadout groups based on the GroupBy list.
    /// Each level of GroupBy creates a nested collapsible subgroup.
    /// When no more GroupBy levels remain, items are added directly.
    /// </summary>
    private void BuildGroupTree(
        BoxContainer parent,
        List<LoadoutPrototype> protos,
        int level,
        HumanoidCharacterProfile profile,
        RoleLoadout loadout,
        ICommonSession session,
        IDependencyCollection collection,
        LoadoutSystem loadoutSystem)
    {
        var protoMan = collection.Resolve<IPrototypeManager>();

        // Group by the key at the current level, or by ID if no more keys
        var groups = protos
            .GroupBy(p => level < p.GroupBy.Count ? p.GroupBy[level] : p.ID)
            .ToDictionary(g => g.Key, g => g.ToList());

        foreach (var (groupKey, groupProtos) in groups)
        {
            var firstProto = groupProtos[0];
            var remainingProtos = groupProtos.Skip(1).ToList();

            // Nuclear-LoadoutGroupTree: single item with no more sub-levels — just a button
            if (remainingProtos.Count == 0 && level >= firstProto.GroupBy.Count)
            {
                parent.AddChild(CreateLoadoutUI(firstProto, profile, loadout, session, collection, loadoutSystem));
                continue;
            }

            // Nuclear-LoadoutGroupTree: create a collapsible group with toggle button
            var firstElement = CreateLoadoutUI(firstProto, profile, loadout, session, collection, loadoutSystem);
            firstElement.HorizontalExpand = true;

            var subContainer = new SubLoadoutContainer
            {
                Name = groupKey,
                Visible = _openedGroups.GetValueOrDefault(groupKey, false)
            };

            var toggle = new ToggleLoadoutButton
            {
                Text = subContainer.Visible ? OpenedGroupMark : ClosedGroupMark,
                Pressed = subContainer.Visible
            };

            toggle.OnPressed += _ =>
            {
                var willOpen = !subContainer.Visible;
                subContainer.Visible = willOpen;
                toggle.Text = willOpen ? OpenedGroupMark : ClosedGroupMark;
                toggle.Pressed = willOpen;
                _openedGroups[groupKey] = willOpen;
            };

            firstElement.AddChild(toggle);
            toggle.SetPositionFirst();

            parent.AddChild(firstElement);
            parent.AddChild(subContainer);

            // Nuclear-LoadoutGroupTree: add remaining items to the subgroup
            // If items have another GroupBy level, nest them deeper; otherwise add flat
            if (remainingProtos.Any(p => level + 1 < p.GroupBy.Count))
            {
                BuildGroupTree(subContainer.Grid, remainingProtos, level + 1, profile, loadout, session, collection, loadoutSystem);
            }
            else
            {
                foreach (var proto in remainingProtos)
                {
                    subContainer.Grid.AddChild(CreateLoadoutUI(proto, profile, loadout, session, collection, loadoutSystem));
                }
            }
        }
    }
    // Nuclear-LoadoutGroupTree-End

    // Nuclear-Edit-Start
    // CreateToggleButton removed — logic has been moved to BuildGroupTree
    /*private ToggleLoadoutButton CreateToggleButton(KeyValuePair<string, List<LoadoutPrototype>> kvp, LoadoutContainer firstElement, SubLoadoutContainer subContainer)
    {
        var toggle = new ToggleLoadoutButton
        {
            Text = ClosedGroupMark
        };

        toggle.Text = subContainer.Visible ? OpenedGroupMark : ClosedGroupMark;
        toggle.Pressed = subContainer.Visible;

        toggle.OnPressed += _ =>
        {
            var willOpen = !subContainer.Visible;
            subContainer.Visible = willOpen;
            toggle.Text = willOpen ? OpenedGroupMark : ClosedGroupMark;
            toggle.Pressed = willOpen;
            _openedGroups[kvp.Key] = willOpen;
        };

        firstElement.AddChild(toggle);
        toggle.SetPositionFirst();
        return toggle;
    }*/

    // UpdateSubGroupSelectedInfo removed — logic has been moved to BuildGroupTree
    /*private void UpdateSubGroupSelectedInfo(LoadoutContainer loadout, string itemName, BoxContainer subList)
    {
        var countSubSelected = subList.Children
            .OfType<LoadoutContainer>()
            .Count(c => c.Select.Pressed);

        if (countSubSelected > 0)
        {
            loadout.Text = Loc.GetString("loadouts-count-items-in-group", ("item", itemName), ("count", countSubSelected));
        }
    }*/
    // Nuclear-Edit-End

    /// <summary>
    /// Creates a UI container for a single Loadout item.
    ///
    /// This method was extracted from RefreshLoadouts because the logic for creating
    /// individual loadout items is used multiple times inside that method, and duplicating
    /// the code made it harder to maintain.
    ///
    /// Logic:
    /// - Checks if the item is currently selected in the loadout.
    /// - Checks if the item is valid for selection (IsValid).
    /// - Creates a LoadoutContainer with the appropriate status (disabled / active).
    /// - Subscribes to button press events to handle selection and deselection.
    /// </summary>
    /// <param name="proto">The loadout item prototype.</param>
    /// <param name="profile">The humanoid character profile.</param>
    /// <param name="loadout">The current role loadout for the user.</param>
    /// <param name="session">The user's session.</param>
    /// <param name="collection">The dependency injection container.</param>
    /// <param name="loadoutSystem">The loadout system instance.</param>
    /// <returns>A fully initialized LoadoutContainer for UI display.</returns>
    private LoadoutContainer CreateLoadoutUI(LoadoutPrototype proto, HumanoidCharacterProfile profile, RoleLoadout loadout, ICommonSession session, IDependencyCollection collection, LoadoutSystem loadoutSystem)
    {
        var selected = loadout.SelectedLoadouts[_groupProto.ID];

        var pressed = selected.Any(e => e.Prototype == proto.ID);

        var enabled = loadout.IsValid(profile, session, proto.ID, collection, out var reason);

        var cont = new LoadoutContainer(proto, !enabled, reason);

        cont.Text = loadoutSystem.GetName(proto);

        cont.Select.Pressed = pressed;

        cont.Select.OnPressed += args =>
        {
            if (args.Button.Pressed)
                OnLoadoutPressed?.Invoke(proto.ID);
            else
                OnLoadoutUnpressed?.Invoke(proto.ID);
        };

        return cont;
    }
}
