using Content.Client._Nuclear.Lobby;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Nuclear.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class ClothingDisplayControl : BoxContainer
{
    public event Action<ClothingDisplayMode>? OnModeChanged;

    private ClothingDisplayMode _mode = ClothingDisplayMode.ShowAll;

    private static readonly string[] ModeLocKeys =
    [
        "humanoid-profile-editor-clothing-show-all",
        "humanoid-profile-editor-clothing-show-underwear",
        "humanoid-profile-editor-clothing-hide-all",
    ];

    public ClothingDisplayControl()
    {
        RobustXamlLoader.Load(this);

        ClothingButton.OnPressed += _ =>
        {
            _mode = (ClothingDisplayMode)(((int)_mode + 1) % 3);
            ClothingButton.Text = Loc.GetString(ModeLocKeys[(int)_mode]);
            OnModeChanged?.Invoke(_mode);
        };

        ClothingButton.Text = Loc.GetString(ModeLocKeys[0]);
    }

    public void SetMode(ClothingDisplayMode mode)
    {
        _mode = mode;
        ClothingButton.Text = Loc.GetString(ModeLocKeys[(int)mode]);
    }
}